import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Coa AI",
  description:
    "Terms of Service for Coa AI, the AI-powered fitness coaching app. Read our terms covering subscriptions, acceptable use, disclaimers, and more.",
  alternates: {
    canonical: "/terms",
  },
  robots: {
    index: false,
    follow: true,
  },
};

export default function TermsOfService() {
  return (
    <section className="max-w-[760px] mx-auto px-5 md:px-10 py-20 md:py-28">
      {/* Back link */}
      <Link
        href="/"
        className="text-sm text-[#5856D6] hover:underline"
      >
        &larr; Back to home
      </Link>

      {/* Label pill */}
      <span className="mt-8 inline-block rounded-full bg-[rgba(88,86,214,0.08)] px-4 py-1.5 text-xs font-bold uppercase tracking-[0.1em] text-[#5856D6]">
        LEGAL
      </span>

      {/* Headline */}
      <h1 className="text-[30px] md:text-[44px] font-[800] text-[#1A1A22] mt-4">
        Terms of Service
      </h1>

      {/* Last updated */}
      <p className="text-sm text-[#A0A0AE] mt-2">Last updated: January 2025</p>

      {/* -- 1. Acceptance of Terms -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        1. Acceptance of Terms
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        By downloading, installing, accessing, or using the Coa AI mobile
        application (&quot;App&quot;) or any associated services (collectively,
        the &quot;Service&quot;), you acknowledge that you have read, understood,
        and agree to be bound by these Terms of Service (&quot;Terms&quot;). If
        you do not agree to these Terms, you must not use the Service.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        We reserve the right to update or modify these Terms at any time. When
        we make changes, we will update the &quot;Last updated&quot; date at the
        top of this page. Your continued use of the Service after any such
        changes constitutes your acceptance of the revised Terms.
      </p>

      {/* -- 2. Description of Service -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        2. Description of Service
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        Coa AI is an artificial-intelligence-powered fitness coaching
        application that provides personalised workout plans, carb-cycled meal
        plans, and a 24/7 AI coach chat experience. The Service is designed to
        help users pursue their fitness goals through data-driven guidance and
        adaptive programming.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        <strong className="text-[#1A1A22]">Important:</strong> The Service is
        provided for informational and educational purposes only. Coa AI does{" "}
        <strong className="text-[#1A1A22]">NOT</strong> provide medical advice,
        diagnosis, or treatment. The workout routines, meal plans, and coaching
        suggestions generated by the AI are not a substitute for professional
        medical advice. Always consult a qualified healthcare professional before
        starting any new exercise programme, nutrition plan, or if you have any
        concerns about your health.
      </p>

      {/* -- 3. User Accounts -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        3. User Accounts
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        To access the full features of Coa AI, you must create an account. Account
        creation is handled via Google OAuth through our authentication provider,
        Clerk. By creating an account you agree to provide accurate and complete
        information during the registration process.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        You are solely responsible for maintaining the confidentiality of your
        account credentials and for all activities that occur under your account.
        You agree to notify us immediately of any unauthorised use of your
        account or any other breach of security. Coa AI will not be liable for
        any loss or damage arising from your failure to protect your account
        information.
      </p>

      {/* -- 4. Subscription & Payments -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        4. Subscription &amp; Payments
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        Coa AI offers premium features through paid subscription plans. All
        subscription purchases and payments are processed through the Google Play
        Store or the Apple App Store (collectively, the &quot;Stores&quot;),
        depending on the platform you use. By subscribing, you agree to the
        payment terms presented to you at the time of purchase.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        Subscriptions automatically renew at the end of each billing period
        unless you cancel before the renewal date. You may manage or cancel your
        subscription at any time through your Store account settings.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        Refund requests are governed by the refund policies of the respective
        Store through which you made your purchase. Coa AI does not directly
        process refunds; please contact Google Play or Apple App Store support
        for refund enquiries.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        We reserve the right to change subscription pricing at any time. If we
        increase prices, we will provide reasonable advance notice so that you
        may cancel your subscription before the new pricing takes effect.
      </p>

      {/* -- 5. Acceptable Use -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        5. Acceptable Use
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        You agree to use the Service only for lawful purposes and in accordance
        with these Terms. When using Coa AI, you must not:
      </p>
      <ul className="list-disc pl-6 text-base leading-[1.75] text-[#6B6B7A] mb-4 space-y-2">
        <li>
          Abuse, harass, or send harmful, threatening, or offensive content
          through the AI coach or any other feature of the Service.
        </li>
        <li>
          Attempt to manipulate, exploit, or &quot;jailbreak&quot; the AI to
          generate responses that promote dangerous activities, self-harm,
          eating disorders, harmful substances, or any other content that could
          endanger health or safety.
        </li>
        <li>
          Use the Service to generate or distribute spam, malware, or any
          content that violates applicable laws or third-party rights.
        </li>
        <li>
          Reverse-engineer, decompile, disassemble, or otherwise attempt to
          extract the source code or underlying algorithms of the Service.
        </li>
        <li>
          Share your account credentials with others or allow multiple
          individuals to use a single account.
        </li>
        <li>
          Interfere with or disrupt the integrity or performance of the Service
          or its related systems and networks.
        </li>
      </ul>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        We reserve the right to investigate and take appropriate action,
        including suspension or termination of your account, if we determine
        that you have violated these acceptable use guidelines.
      </p>

      {/* -- 6. Intellectual Property -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        6. Intellectual Property
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        All content included in or made available through the Service, including
        but not limited to text, graphics, logos, icons, images, audio clips,
        AI-generated workout plans, AI-generated meal plans, software, and
        branding, is the property of Coa AI or its licensors and is protected by
        applicable copyright, trademark, and other intellectual property laws.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        The Coa AI name, logo, and all related names, logos, product and service
        names, designs, and slogans are trademarks of Coa AI. You may not use
        such marks without our prior written permission.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        You are granted a limited, non-exclusive, non-transferable, revocable
        licence to access and use the Service for your personal, non-commercial
        fitness purposes. This licence does not include the right to reproduce,
        distribute, publicly display, or create derivative works from any
        content provided through the Service without our express written consent.
      </p>

      {/* -- 7. Disclaimer of Warranties -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        7. Disclaimer of Warranties
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        The Service, including all AI-generated fitness plans, nutrition
        guidance, and coaching suggestions, is provided on an{" "}
        <strong className="text-[#1A1A22]">&quot;as is&quot;</strong> and{" "}
        <strong className="text-[#1A1A22]">&quot;as available&quot;</strong>{" "}
        basis without warranties of any kind, whether express or implied. To the
        fullest extent permitted by applicable law, Coa AI disclaims all
        warranties, including but not limited to implied warranties of
        merchantability, fitness for a particular purpose, and non-infringement.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        AI-generated fitness plans, workout routines, and nutrition advice are
        for{" "}
        <strong className="text-[#1A1A22]">
          informational purposes only
        </strong>{" "}
        and do <strong className="text-[#1A1A22]">NOT</strong> constitute
        medical advice. Individual results may vary. You should always consult a
        qualified physician or healthcare provider before beginning any exercise
        or diet programme, especially if you have pre-existing health conditions,
        injuries, or are taking medication.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        Coa AI does not warrant that the Service will be uninterrupted,
        error-free, secure, or free of viruses or other harmful components. We
        do not guarantee the accuracy, completeness, or usefulness of any
        AI-generated content or any information provided through the Service.
      </p>

      {/* -- 8. Limitation of Liability -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        8. Limitation of Liability
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        To the maximum extent permitted by applicable law, Coa AI, its
        officers, directors, employees, agents, and affiliates shall not be
        liable for any indirect, incidental, special, consequential, or punitive
        damages, including but not limited to loss of profits, data, use, or
        goodwill, arising out of or in connection with your access to or use of
        (or inability to use) the Service.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        Without limiting the foregoing, Coa AI shall not be liable for any
        personal injuries, health issues, physical harm, or damages of any kind
        arising from your reliance on AI-generated workout plans, meal plans,
        nutrition advice, or any other content provided through the Service. You
        use the Service and follow any fitness or nutritional guidance entirely
        at your own risk.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        In no event shall Coa AI&apos;s total liability to you for all claims
        arising out of or relating to these Terms or the Service exceed the
        amount you paid to Coa AI, if any, during the twelve (12) months
        immediately preceding the event giving rise to the claim.
      </p>

      {/* -- 9. Termination -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        9. Termination
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        We reserve the right to suspend or terminate your account and access to
        the Service, without prior notice or liability, at our sole discretion,
        for any reason, including but not limited to a breach of these Terms,
        engaging in prohibited conduct, or any activity that we believe is
        harmful to other users or the integrity of the Service.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        You may delete your account at any time through the App&apos;s account
        settings or by contacting us at the email address provided below. Upon
        termination or deletion, your right to use the Service will immediately
        cease. Any data associated with your account may be deleted in
        accordance with our Privacy Policy, except where retention is required by
        law.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        All provisions of these Terms that by their nature should survive
        termination shall survive, including without limitation ownership
        provisions, warranty disclaimers, indemnity provisions, and limitations
        of liability.
      </p>

      {/* -- 10. Governing Law -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        10. Governing Law
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        These Terms shall be governed by and construed in accordance with the
        laws of the jurisdiction in which Coa AI operates, without regard to its
        conflict-of-law provisions. You agree to submit to the personal and
        exclusive jurisdiction of the courts located within that jurisdiction for
        the resolution of any disputes arising out of or relating to these Terms
        or the Service.
      </p>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        If any provision of these Terms is found to be invalid or unenforceable
        by a court of competent jurisdiction, the remaining provisions shall
        continue in full force and effect. Our failure to enforce any right or
        provision of these Terms shall not constitute a waiver of such right or
        provision.
      </p>

      {/* -- 11. Contact Information -- */}
      <h2 className="text-[32px] font-bold text-[#1A1A22] mt-12 mb-4">
        11. Contact Information
      </h2>
      <p className="text-base leading-[1.75] text-[#6B6B7A] mb-4">
        If you have any questions, concerns, or feedback regarding these Terms of
        Service, please contact us:
      </p>
      <ul className="list-disc pl-6 text-base leading-[1.75] text-[#6B6B7A] mb-4 space-y-2">
        <li>
          <strong className="text-[#1A1A22]">Email:</strong>{" "}
          <a
            href="mailto:support@coaai.app"
            className="text-[#5856D6] hover:underline"
          >
            support@coaai.app
          </a>
        </li>
        <li>
          <strong className="text-[#1A1A22]">Contact page:</strong>{" "}
          <Link href="/contact" className="text-[#5856D6] hover:underline">
            coaai.app/contact
          </Link>
        </li>
      </ul>
    </section>
  );
}
